### ISSUE TITLE
[question] jsonlint vs jq

### ISSUE THREAD

**Issue by digitalnomd** [circlecell/jsonlint.com#87]
What does jsonlint give you that using jq wouldn't? Specifically I'm trying to understand the tradeoffs between the two tools. I'm away that jq is used primarily for parsing JSON but it can be used as a quick validation as well (although maybe not in a strict sense).

**Comment by finom** [comment]
The main reason is that jsonlint is written on JS. If we'd use jq we'd need to have a server and send potentially secure data there or somehow port the library to webassembly which can be too hard (but we didn't try that though). But I can't answer you what is better in terms of their functioning because it would require to make a research which also may take a lot of time.
