### ISSUE TITLE
security question 

### ISSUE THREAD

**Issue by AliGU23** [circlecell/jsonlint.com#96]
Hello

I would like to know if you site retains data and if so for how long. How will my data be protected once I paste on your site. 
Thank you 
Alice

**Comment by TobiasWenzel** [comment]
I had the same question, because on the start page there is no statement at all about privacy. In the linked privacy document, however, there is nothing written about the JSON data being collected.

To verify that, you can open your browser's developer console, switch to the network tab and check if anything is being POSTed to the server. In my tries there was nothing. So it is a pure browser application, all linting, formatting & verification is done only locally on your computer.

I also had a quick look at the sources and found no place where the pasted data is sent anywhere to a server.

**Comment by toddynho** [comment]
Correct - we don't save anything entered. The same code used on the live site is what is here in this repo.
